### ISSUE TITLE
problems when using 'merge.py'

### ISSUE THREAD

**Issue by wjxiz1992** [chuanqi305/MobileNet-SSD#12]
Hi, chuanqi305:
    I've successfully trained my own dataset with your code, and my number of classes is 5. 
    When I tried to use your 'merge.py' to get the deploy model, I firstly got the error: 

> KeyValue Error :  'conv11_mbox_conf_new'.

So to solve this, need to rename 6 *_mbox_conf layers in deploy prototxt.

And know I got the new error: (I've already modify the num_output in both deploy and train prototxt)

`
I0807 11:20:04.707312 18966 net.cpp:434] mbox_priorbox <- conv11_mbox_priorbox

I0807 11:20:04.707326 18966 net.cpp:434] mbox_priorbox <- conv13_mbox_priorbox

I0807 11:20:04.707340 18966 net.cpp:434] mbox_priorbox <- conv14_2_mbox_priorbox

I0807 11:20:04.707352 18966 net.cpp:434] mbox_priorbox <- conv15_2_mbox_priorbox

I0807 11:20:04.707366 18966 net.cpp:434] mbox_priorbox <- conv16_2_mbox_priorbox

I0807 11:20:04.707379 18966 net.cpp:434] mbox_priorbox <- conv17_2_mbox_priorbox

I0807 11:20:04.707396 18966 net.cpp:408] mbox_priorbox -> mbox_priorbox

I0807 11:20:04.707414 18966 net.cpp:150] Setting up mbox_priorbox

I0807 11:20:04.707429 18966 net.cpp:157] Top shape: 1 2 7668 (15336)

I0807 11:20:04.707442 18966 net.cpp:165] Memory required for data: 87688080

I0807 11:20:04.707453 18966 layer_factory.hpp:77] Creating layer mbox_conf_reshape

I0807 11:20:04.707469 18966 net.cpp:100] Creating Layer mbox_conf_reshape

I0807 11:20:04.707481 18966 net.cpp:434] mbox_conf_reshape <- mbox_conf

I0807 11:20:04.707496 18966 net.cpp:408] mbox_conf_reshape -> mbox_conf_reshape

F0807 11:20:04.707522 18966 reshape_layer.cpp:80] Check failed: 0 == bottom[0]->count() % 

explicit_count (0 vs. 9) bottom count (9585) must be divisible by the product of the specified dimensions (21)
`

I don't know where to modify now. 
Waiting for you suggestion.
Thanks

**Comment by wjxiz1992** [comment]
Hi, sry. I just found how to solve it.

I also need to change the other 2 params in deploy prototxt: 
 "num_classes" in  "detection_out" layer and "dim" in "mbox_conf_reshape" layer.
change 21 to my 5.

**Comment by pierrelzw** [comment]
@wjxiz1992 's solution works for me
