### ISSUE TITLE
why don't convolution depth wise  use engine: CUDNN instead of engine: Caffe? 

### ISSUE THREAD

**Issue by 0801130205** [chuanqi305/MobileNet-SSD#122]
In the layers of conv1/dw and conv2/dw and so on  in MobileNet-SSD/train.prototxt,  setting engine: CAFFE  that means the layers can't use gpu to speed up. So why not  use engine: CUDNN?

**Comment by chuanqi305** [comment]
@0801130205 on some types of GPU, use engine:CUDNN will cause crash. If no crash, use CUDNN is better.
