### ISSUE TITLE
add conversion script from tensorflow to caffemodel?

### ISSUE THREAD

**Issue by kodonnell** [chuanqi305/MobileNet-SSD#133]
@chuanqi305 I've seen it mentioned before that you convert the tensorflow model to numpy and then into caffe - but I can't see this script. Could you add it please? I understand that this will only work for this architecture etc. but it'll still be useful.

**Comment by chuanqi305** [comment]
@kodonnell see [MobilenetV2-SSD](https://github.com/chuanqi305/MobileNetv2-SSDLite)

**Comment by kodonnell** [comment]
Excellent. It might pay to add this to the readme for others, but I'll close this now. Great work!
