### ISSUE TITLE
PriorBox layer

### ISSUE THREAD

**Issue by ryusaeba** [chuanqi305/MobileNet-SSD#16]
Hi @chuanqi305 , 

I saw there has [step in weiliu's PriorBox](https://github.com/weiliu89/caffe/blob/ssd/examples/ssd/score_ssd_pascal.py#L329) layer but it doesn't exist in your [prototxt](https://github.com/chuanqi305/MobileNet-SSD/blob/master/template/MobileNetSSD_train_template.prototxt). Is this intentional?

**Comment by chuanqi305** [comment]
The default step is img_width / layer_width, img_height / layer_height.
 For the first step, 300 / 19 = 15.

**Comment by ryusaeba** [comment]
OK, I think I have to read the code . Thanks!
