### ISSUE TITLE
person getting detected as aeroplane

### ISSUE THREAD

**Issue by AbhimanyuAryan** [chuanqi305/MobileNet-SSD#168]
I'm running this demo.py on standard model 7500-iteration to test....but there's some weird output 

![2](https://user-images.githubusercontent.com/8083613/63406686-418c3180-c408-11e9-8d49-de66ca97c4cf.png)
![1](https://user-images.githubusercontent.com/8083613/63406687-418c3180-c408-11e9-8da4-7f0e50c0bbf0.png)

**Comment by Samjith888** [comment]
which tool you used for labeling the image?  Will you show your labelled file?

**Comment by AbhimanyuAryan** [comment]
@Samjith888 it's default model. I didn't do anything. I ran default stuff with demo.py
