### ISSUE TITLE
error in running demo.py

### ISSUE THREAD

**Issue by kaishijeng** [chuanqi305/MobileNet-SSD#17]
I downloaded your pretrained model and got the following error when running python demo.py.
SSD-caffe is compiled with CPU mode only since I don't have a graphic card. Any idea why this error happens.

/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module numpy was already imported from /usr/local/lib/python2.7/dist-packages/numpy/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
/usr/local/lib/python2.7/dist-packages/google/protobuf/__init__.py:37: UserWarning: Module six was already imported from /usr/local/lib/python2.7/dist-packages/six.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  __import__('pkg_resources').declare_namespace(__name__)
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0814 19:52:40.115876 17813 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W0814 19:52:40.115895 17813 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W0814 19:52:40.115898 17813 _caffe.cpp:142] Net('MobileNetSSD_deploy.prototxt', 1, weights='MobileNetSSD_deploy.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 1177:17: Message type "caffe.LayerParameter" has no field named "permute_param".
F0814 19:52:40.117127 17813 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: MobileNetSSD_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)

**Comment by chuanqi305** [comment]
Seems that your ssd environment is not correctly configured. Please try some other models to check  ssd is available.

**Comment by kaishijeng** [comment]
Yes, you are correct.

Thanks,

**Comment by IEEE-FELLOW** [comment]
@kaishijeng hi,have u solved ur problems???? I got the same error as u

**Comment by manjupavithraa** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
W1203 20:03:55.584233  8415 _caffe.cpp:139] DEPRECATION WARNING - deprecated use of Python interface
W1203 20:03:55.584311  8415 _caffe.cpp:140] Use this instead (with the named "weights" parameter):
W1203 20:03:55.584326  8415 _caffe.cpp:142] Net('MobileNetSSD_deploy.prototxt', 1, weights='MobileNetSSD_deploy.caffemodel')
[libprotobuf ERROR google/protobuf/text_format.cc:274] Error parsing text-format caffe.NetParameter: 1177:17: Message type "caffe.LayerParameter" has no field named "permute_param".
F1203 20:03:55.586704  8415 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: MobileNetSSD_deploy.prototxt
*** Check failure stack trace: ***
Aborted (core dumped)


Iam getting the above error.I dont know why this error ocuurs.Can you suggest me why this happens?

**Comment by TernaK** [comment]
Did you checkout the ssd branch https://github.com/weiliu89/caffe/tree/ssd?

**Comment by himanimadaan** [comment]
I'm getting the same error. Any lead on how to tackle this?
