### ISSUE TITLE
How to set anchor box parameters?

### ISSUE THREAD

**Issue by wjxiz1992** [chuanqi305/MobileNet-SSD#22]
Hi Chuanqi, appreciate your work! 
I have a question, how can I set the number of defaut boxes?(For weiliu's SSD, its first priorbox layer has 4 defaut boxes instead of your 3.) It seems that if I want to change it, I need to rebuild the whole model. 
Looking forward for your suggestions.

**Comment by chuanqi305** [comment]
see gen.py:
```
def create_ssd_anchors(num_layers=6,
                       min_scale=0.2,
                       max_scale=0.95):
  box_specs_list = []
  scales = [min_scale + (max_scale - min_scale) * i / (num_layers - 1)
            for i in range(num_layers)] + [1.0]
  return zip(scales[:-1], scales[1:])
```
