### ISSUE TITLE
The parameters problem(num of priorbox)

### ISSUE THREAD

**Issue by wjxiz1992** [chuanqi305/MobileNet-SSD#23]
https://github.com/chuanqi305/MobileNet-SSD/blob/daef68a6c2f5fbb8c88404266aa28180646d17e0/gen.py#L748

Hi, chuanqi305, why the parameter here is 3 ,not 4? Because according to weiliu89's source code in "prior_box_layer.cpp", if aspect ratio = [2.0], there should be 4 default boxes, their width are:
1. aspect = 1.0 width = min_size
2.aspect = 1.0 width = sqrt(min_size*max_size)
3. aspect = 2.0 width = min_size * sqrt(2.0)
4. aspect = 1/2.0 width = min_size * sqrt(1/2.0)

Thanks for your explanation here.

**Comment by chuanqi305** [comment]
I followed tensorflow's config, 3 anchors for conv11, without
 2.aspect = 1.0 width = sqrt(min_size*max_size)

**Comment by wjxiz1992** [comment]
Hi chuanqi305, I am a deep learning engineer in NVIDIA, could you please
share your WeChat number and discuss more?

2017-08-28 8:55 GMT+08:00 chuanqi305 <notifications@github.com>:

**Comment by Aspirinkb** [comment]
Hi @chuanqi305 where can I find tensorflow's mobilenet(v2) ssd config? I downloaded its source code (tensorflow-models) but did not find the config details about conv11 layer's anchors.
