### ISSUE TITLE
merge error

### ISSUE THREAD

**Issue by nj0904107027** [chuanqi305/MobileNet-SSD#31]
when I use merge_bn.py to output deploy.prototxt ,but it appeares the  KeyError: 'convll_mbox_conf_new' 。can you tell what the error happened? thanks very much.

**Comment by dlyldxwl** [comment]
Because the deploy.prototxt that you use don't have the layer of  conv11_mbox_conf_new,you should use deploy.prototxt of example file than MobileNet-SSD file.

**Comment by birdwcp** [comment]
I use merge_bn.py with my own mobilenet-ssd network , it appeares  ' nob.params[key][1].data[...] = bias    IndexError: Index out of range'
I don't know what's wrong with it, can you tell me how to use merge_bn.py?

**Comment by birdwcp** [comment]
@dlyldxwl 
I use merge_bn.py with my own mobilenet-ssd network , it appeares ' nob.params[key][1].data[...] = bias IndexError: Index out of range'
I don't know what's wrong with it, can you tell me how to use merge_bn.py?  thx

**Comment by birdwcp** [comment]
I fix it.  the  param (bias_term) of my conv layer is false ...

**Comment by nj0904107027** [comment]
thanks

**Comment by datamonday** [comment]
I met this same error and I edit the  " deploy_proto = 'example/MobileNetSSD_deploy.prototxt' " in merge_n.py.It has merged now.

**Comment by wtiandong** [comment]
@datamonday is right, in example/MobileNetSSD_deploy.prototxt, bias_term is true by default, thus nob.params[key][1].data[...] can be indexed.

**Comment by AbhimanyuAryan** [comment]
how to fix it? @wtiandong @datamonday @nj0904107027 @birdwcp @dlyldxwl ? 

Please help me out. I'm using this merge_bn.py https://github.com/tolotrasamuel/real-time-object-detection-retraining-ncs-raspberry-pi/blob/master/examples/MobileNet-SSD/merge_bn.py

Also, this is the issue I have created https://github.com/tolotrasamuel/real-time-object-detection-retraining-ncs-raspberry-pi/issues/1

**Comment by AbhimanyuAryan** [comment]
yaa you need to change deploy.prototxt....check this: https://github.com/tolotrasamuel/real-time-object-detection-retraining-ncs-raspberry-pi/blob/master/examples/MobileNet-SSD/example/MobileNetSSD_deploy.prototxt
