### ISSUE TITLE
Failed to start an training using my own data

### ISSUE THREAD

**Issue by oishi89** [chuanqi305/MobileNet-SSD#39]
Hi I'm trying to train a model using my own data that have only one class. I created my labelmap.prototxt like that

```
item {
  name: "none_of_the_above"
  label: 0
  display_name: "background"
}
item {
  name: "hand"
  label: 1
  display_name: "hand"
}

```

then I run the script `./gen_model.sh 2`
Start a training `./train.sh`

<img width="1096" alt="screen shot 2017-10-28 at 3 44 32 pm" src="https://user-images.githubusercontent.com/3854757/32139177-f01ec6e8-bbf6-11e7-9d72-5e13f2e5bed6.png">

I'm not sure do i need a label for ` none_of_the_above  = background` and my class number should be 1 or 2 

Thanks

**Comment by chuanqi305** [comment]
@oishi89 Change the batch size in train.prototxt, current size is 32, try 24 , 16 or 8.

**Comment by oishi89** [comment]
@chuanqi305 current size is 24 in train.prototxt I'm going to change to 16. How about test.prototxt ?  currently the batch size in test.prototxt is 8 ? Do I need to update both to 16 or 8 ?

**Comment by chuanqi305** [comment]
@oishi89 No, the batch size in the test.prototxt need not to be the same as in the train.prototxt.
If memory issue in test stage, you can also change the batch size in the test.prototxt to 4 or 2.
test_iter * batch = test_image_number

**Comment by oishi89** [comment]
Thanks @chuanqi305 it's working now 👍
