### ISSUE TITLE
num of mbox_conf layers

### ISSUE THREAD

**Issue by wjxiz1992** [chuanqi305/MobileNet-SSD#4]
Hi chuanqi305,
I tried to train my own dataset according to your instructions, and I found that there're 6 mbox_conf layers: conv11, conv13, conv14_2, conv15_2, conv16_2, conv17_2. It's a mistake or I misunderstand someting here?

One more question: why should I change the name of mbox_conf layers? If I change the names, we should also change the name for some "bottom" and "top" names, right? 

Thanks.

**Comment by chuanqi305** [comment]
For the conv11 layer， mbox_conf output is 63 = 21 * 3,
and for the other layers, mbox_conf output is 126 = 21 * 6.
You need not change the bottom and top names, just change the name of mbox_conf layers, to avoid weight shape conflict (if your class number is just the same as VOC, there is no conflict).
