### ISSUE TITLE
where is MobileNetSSD_train.caffemodel?

### ISSUE THREAD

**Issue by zhenxing9968** [chuanqi305/MobileNet-SSD#5]
where is MobileNetSSD_train.caffemodel?

**Comment by chuanqi305** [comment]
Download it from the link(googledrive) in the README.

**Comment by zhenxing9968** [comment]
@chuanqi305 But I just found MobileNetSSD_deploy.caffemodel and mobilenet_iter_73000.caffemodel in the readme.

**Comment by chuanqi305** [comment]
Yes, mobilenet_iter_73000.caffemodel is MobileNetSSD_train.caffemodel, I has fixed it. By the way,  I removed the unused large files from the repository, please clone the project again.

**Comment by zhenxing9968** [comment]
got it, ths, but I use the MobileNetSSD_deploy.caffemodel to detect person in the picture，I found the effect is very poor，do you know this situation?
could you share your pre_trained model just like VGG_ILSVRC_16_layers_fc_reduced.caffemodel in SSD?

**Comment by chuanqi305** [comment]
I started from MobileNet [classifier](https://drive.google.com/open?id=0B3gersZ2cHIxZi13UWF0OXBsZzA).

**Comment by zhenxing9968** [comment]
OK 
Thank you very much
