### ISSUE TITLE
About problems of  coco train 

### ISSUE THREAD

**Issue by dlyldxwl** [chuanqi305/MobileNet-SSD#53]
Thanks for your job!
 you first trained the model on MS-COCO and then fine-tuned on VOC0712, are you using coco2017 or coco2014?   SSD author  gives the method of making coco2014 data set,  that need other json file-instances_minival2014.json and instances_valminusminival2014.json. 
but I don't find  instances_minival2017.json and instances_valminusminival2017.json，
can you tell me the links of these file? 
thanks

**Comment by priyanka-chaudhary** [comment]
I have a similar issue. Can you tell me where you found the file instances_valminusminival2017.json?

**Comment by ujsyehao** [comment]
I have these json files.
