### ISSUE TITLE
Computing FPS

### ISSUE THREAD

**Issue by Allisonlyu** [chuanqi305/MobileNet-SSD#60]
Hi chuanqi,

I tested your pre-trained model on P40 and got the result that the speed was around 7 fps. I tested another tensorflow ver(15fps on P40) and actually your ssd version run much faster than that. I added the computation code as follows:
    start = time.time()
    out = net.forward()
    end = time.time()
    box, conf, cls = postprocess(origimg, out)
    seconds = end - start
    # Calculate frames per second
    fps = 1 / seconds
    print("Estimated frames per second : {0}".format(fps))

And here is the results:
Estimated frames per second : 6.94888285835
1516129934.75
1516129934.89
0.144336938858

Should I use the time cost of 'out = net.forward()' to compute the speed?
Many thanks!

**Comment by youngwanLEE** [comment]
@Allisonlyu ,

You said,
mobilenet-ssd caffe ver. : 7FPS
mobilenet-ssd tf ver. : 15FPS 
Then, tf vers. run faster than caffe.ver?
