### ISSUE TITLE
no output detections

### ISSUE THREAD

**Issue by sfraczek** [chuanqi305/MobileNet-SSD#64]
Hey, I am running your deploy model (caffemodel + prototxt + voc labelmap) in intel caffe framework (not using python scripts) but there are no detections found.
When I run normal voc and coco models everything seems fine, but your model has high speed but I can't see any detections at all.
Do I have to do this rescaling of images?
```
img = img - 127.5
img = img * 0.007843
```

**Comment by sfraczek** [comment]
That worked. :)

**Comment by sainisanjay** [comment]
@sfraczek May i know how did you resolve

**Comment by sfraczek** [comment]
I couldn't see detections in the output, but after I rescaled the pixel values as in the code section in my first post, it started working. I found people experiencing similar problems online.
