### ISSUE TITLE
Training Log

### ISSUE THREAD

**Issue by soyebn** [chuanqi305/MobileNet-SSD#7]
Will it be possible for you to share your training log which gives 72.7 det accuracy on VOC0712? 

I am trying to train using base network provided at https://github.com/shicai/MobileNet-Caffe. I am using Caffe-SSD, 300x300 script so it is little different from your script but wanted to compare if my training is progressing fine or not.

Thanks.
Soyeb

**Comment by chuanqi305** [comment]
Sorry, I trained this model with adjusting the learning rate many times and the training log is not saved.
You can follow the README to reproduce this result.Getting mAP > 65  is easy, but 72.7 took me too much time.
