### ISSUE TITLE
merge_bn.py AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'

### ISSUE THREAD

**Issue by MichaelQWang** [chuanqi305/MobileNet-SSD#93]
Hi chuanqi,
I install ncs(https://github.com/movidius/ncsdk),the ssd-caffe path is /opt/movidius/ssd-caffe/.
When i run merge_bn.py file,it's output is AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'.how to tackle this problem?
Thanks in advance.

#####################################
I0526 14:59:43.139652  7526 net.cpp:228] conv3 does not need backward computation.
I0526 14:59:43.139660  7526 net.cpp:228] conv3/dw/relu does not need backward computation.
I0526 14:59:43.139668  7526 net.cpp:228] conv3/dw does not need backward computation.
I0526 14:59:43.139673  7526 net.cpp:228] conv2/relu does not need backward computation.
I0526 14:59:43.139681  7526 net.cpp:228] conv2 does not need backward computation.
I0526 14:59:43.139706  7526 net.cpp:228] conv2/dw/relu does not need backward computation.
I0526 14:59:43.139744  7526 net.cpp:228] conv2/dw does not need backward computation.
I0526 14:59:43.139750  7526 net.cpp:228] conv1/relu does not need backward computation.
I0526 14:59:43.139756  7526 net.cpp:228] conv1 does not need backward computation.
I0526 14:59:43.139761  7526 net.cpp:228] conv1/dw/relu does not need backward computation.
I0526 14:59:43.139766  7526 net.cpp:228] conv1/dw does not need backward computation.
I0526 14:59:43.139771  7526 net.cpp:228] conv0/relu does not need backward computation.
I0526 14:59:43.139776  7526 net.cpp:228] conv0 does not need backward computation.
I0526 14:59:43.139782  7526 net.cpp:228] data_input_0_split does not need backward computation.
I0526 14:59:43.139787  7526 net.cpp:228] input does not need backward computation.
I0526 14:59:43.139792  7526 net.cpp:270] This network produces output detection_out
I0526 14:59:43.139940  7526 net.cpp:283] Network initialization done.
Traceback (most recent call last):
  File "merge_bn.py", line 62, in <module>
    merge_bn(net, net_deploy)
  File "merge_bn.py", line 21, in merge_bn
    for key in net.params.iterkeys():
AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'
michael@ubt1604:~/workspace/MobileNet-SSD$

**Comment by fraukej** [comment]
@MichaelQWang This problem is a result from python2 -> python3 conversion.
I assume you are using python3. However, the script is written for python2 usage.
In python3, the `iterkeys` function is replaced with `keys`.

HTH.
