### ISSUE TITLE
add feature map 38x38

### ISSUE THREAD

**Issue by OMG59E** [chuanqi305/MobileNet-SSD#98]
Hi:
     i want to add feature map 38x38 and remove 2x2.  Is it feasible？

**Comment by ujsyehao** [comment]
@OMG59E the origin SSD has 38x38 feature map, it is okay.

**Comment by xizi** [comment]
origin VGG-SSD 有38*38的feature map并用作检测，但MobileNet-SSD里面没有把38*38的feature map用于检测。
